# Ch03 - NumPy

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
type(a) #n-dimensional array

numpy.ndarray

In [4]:
a.dtype #data type obviously

dtype('int64')

In [6]:
a.ndim 

1

In [7]:
a.size

3

In [8]:
a.shape #a tuple of N-positive integers that specifies the size for
#each dimension
#the dimensions are defined as axes and the number of axes is the rank

(3,)

In [9]:
b = np.array([[1.3, 2.4], [0.3, 4.1]]) #numpy arrays don't change shape
b.dtype

dtype('float64')

In [10]:
b.ndim

2

In [11]:
b.size

4

In [12]:
b.shape

(2, 2)

In [13]:
b.itemsize #shows in bytes the size of each item in the array

8

In [14]:
b.data

### Create an Array

In [15]:
c = np.array([[1, 2, 3], [4, 5, 6]])
c

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
d = np.array(((1, 2, 3), (4, 5, 6)))
d

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
e = np.array([(1,2,3),[4,5,6],(7,8,9)])
e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Types of Data

In [18]:
g = np.array([['a','b'],['c','d']])
g

array([['a', 'b'],
       ['c', 'd']],
      dtype='<U1')

In [19]:
g.dtype

dtype('<U1')

In [20]:
g.dtype.name

'str32'

In [21]:
f = np.array([[1,2,3],[4,5,6]], dtype=complex)
f

array([[ 1.+0.j,  2.+0.j,  3.+0.j],
       [ 4.+0.j,  5.+0.j,  6.+0.j]])

### Intrinsic Creation of an Array

In [22]:
np.zeros((3, 3))


array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [23]:
np.ones((3,3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [24]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(4, 10) #first is starting value and 2nd is final value

array([4, 5, 6, 7, 8, 9])

In [26]:
np.arange(0, 12, 3) #the 3rd number represents the gap between 1 and next

array([0, 3, 6, 9])

In [27]:
np.arange(0, 6, 0.6) #3rd can also be a float

array([ 0. ,  0.6,  1.2,  1.8,  2.4,  3. ,  3.6,  4.2,  4.8,  5.4])

In [28]:
np.arange(0,12).reshape(3,4) #using reshape to create 3 rows, 4 cols

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
np.linspace(0,10,5) #similar to arange but 3rd number
                    #defines how many elements we want interval to be
                    #split

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [33]:
np.random.random(3) #np.random is the module and .random is the func inside

array([ 0.5407135 ,  0.81292423,  0.04138215])

In [34]:
np.random.random((3,3)) #this also can create a multi-dim array

array([[ 0.07497797,  0.99022547,  0.36793814],
       [ 0.89843758,  0.70419314,  0.46950216],
       [ 0.49095942,  0.76647274,  0.65070033]])

### Basic Operations

In [35]:
a = np.arange(4)
print(a)
print(a+4)
print(a*2) #can do basic operations -> element-wise

[0 1 2 3]
[4 5 6 7]
[0 2 4 6]


In [36]:
b = np.arange(4,8)
b

array([4, 5, 6, 7])

In [37]:
a + b

array([ 4,  6,  8, 10])

In [38]:
a - b

array([-4, -4, -4, -4])

In [39]:
a * b

array([ 0,  5, 12, 21])

In [40]:
a * np.sin(b) #these operators are also avail. for func's provided
                #that a narray is returned

array([-0.        , -0.95892427, -0.558831  ,  1.9709598 ])

In [41]:
a * np.sqrt(b)

array([ 0.        ,  2.23606798,  4.89897949,  7.93725393])

In [42]:
A = np.arange(0, 9).reshape(3,3)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [43]:
B = np.ones((3,3))
B

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [44]:
A * B

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

### The Matrix Product

In [45]:
np.dot(A,B) #this is NOT element-wise like previous operators

array([[  3.,   3.,   3.],
       [ 12.,  12.,  12.],
       [ 21.,  21.,  21.]])

In [46]:
A.dot(B) #can also be written as an object's fuction of the 2 matrices

array([[  3.,   3.,   3.],
       [ 12.,  12.,  12.],
       [ 21.,  21.,  21.]])

In [47]:
np.dot(B,A) #of course order matters in matrix multiplication

array([[  9.,  12.,  15.],
       [  9.,  12.,  15.],
       [  9.,  12.,  15.]])

### Inrement and Decrement Operators

In [48]:
# actually no such thing in python as there is no ++ or -- (as in C)
#similiar but instead of creating new array it just modifies old array
a = np.arange(4)
print(a)
a += 1
print(a)
a -= 1
print(a)

[0 1 2 3]
[1 2 3 4]
[0 1 2 3]


In [49]:
a = np.arange(4)
print(a)
a += 4
print(a)
a *= 2
print(a)

[0 1 2 3]
[4 5 6 7]
[ 8 10 12 14]


### Universal Functions

In [50]:
#operates on an array in an element by element fashion
#therefore the size is the same as the input
a = np.arange(1,5)
print(a)
print(np.sqrt(a))
print(np.log(a))
print(np.sin(a))

[1 2 3 4]
[ 1.          1.41421356  1.73205081  2.        ]
[ 0.          0.69314718  1.09861229  1.38629436]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


### Aggregate Functions

In [51]:
a = np.array([3.3, 4.5, 1.2, 5.7, 0.3])
print(a)
print(a.sum())
print(a.min())
print(a.max())
print(a.mean())
print(a.std())


[ 3.3  4.5  1.2  5.7  0.3]
15.0
0.3
5.7
3.0
2.00798406368
